### ISSUE TITLE
Module not found: Error: Can't resolve '@elastic/datemath'

### ISSUE THREAD

**Issue by rafaelcarsetimo** [iurynogueira/kibana-datepicker#1]
Hi Iury,

The module dont work in Kibana 6.3.0. Can you verify please?

`Jun 27 10:32:59 elkserver kibana: {"type":"log","@timestamp":"2018-06-27T13:32:59Z","tags":["info","optimize"],"pid":18116,"message":"Optimizing and caching bundles for ml, stateSessionStorageRedirect, status_page, timelion, graph, monitoring, login, logout, dashboardViewer, apm and kibana. This may take a few minutes"}
Jun 27 10:41:54 elkserver kibana: {"type":"error","@timestamp":"2018-06-27T13:41:54Z","tags":["fatal"],"pid":18116,"level":"fatal","error":{"message":"Optimizations failure.\n   6149 modules\n    \n    \u001b[1m\u001b[31mERROR in /usr/share/kibana/plugins/kibana-datepicker/public/datepickerController.js\n    Module not found: Error: Can't resolve '@elastic/datemath' in '/usr/share/kibana/plugins/kibana-datepicker/public'\u001b[39m\u001b[22m\n","name":"Error","stack":"Error: Optimizations failure.\n   6149 modules\n    \n    \u001b[1m\u001b[31mERROR in /usr/share/kibana/plugins/kibana-datepicker/public/datepickerController.js\n    Module not found: Error: Can't resolve '@elastic/datemath' in '/usr/share/kibana/plugins/kibana-datepicker/public'\u001b[39m\u001b[22m\n\n    at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:245:27)\n    at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:28:26)\n    at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:241:12)\n    at applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:514:14)\n    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)\n    at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/CachePlugin.js:78:5)\n    at Compiler.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)\n    at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:511:11)\n    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)\n    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:671:19)\n    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)\n    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:662:11)\n    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)\n    at Compilation.<anonymous> (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/index.js:244:6)\n    at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:204:14)\n    at Compilation.compilation.plugin (/usr/share/kibana/node_modules/webpack/lib/BannerPlugin.js:67:5)\n    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)\n    at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:657:10)\n    at next (/usr/share/kiban /node_modules/tapable/lib/Tapable.js:202:11)\n    at Compilation.<anonymous> (/usr/share/kibana/node_modules/extract-text-webpack-plugin/dist/index.js:275:11)\n    at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)\n    at sealPart2 (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:653:9)"},"message":"Optimizations failure.\n   6149 modules\n    \n    ERROR in /usr/share/kibana/plugins/kibana-datepicker/public/datepickerController.js\n    Module not found: Error: Can't resolve '@elastic/datemath' in '/usr/share/kibana/plugins/kibana-datepicker/public'\n"}
Jun 27 10:41:54 elkserver kibana: FATAL { Error: Optimizations failure.
Jun 27 10:41:54 elkserver kibana: 6149 modules
Jun 27 10:41:54 elkserver kibana: #033[1m#033[31mERROR in /usr/share/kibana/plugins/kibana-datepicker/public/datepickerController.js
Jun 27 10:41:54 elkserver kibana: Module not found: Error: Can't resolve '@elastic/datemath' in '/usr/share/kibana/plugins/kibana-datepicker/public'#033[39m#033[22m
Jun 27 10:41:54 elkserver kibana: at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:245:27)
Jun 27 10:41:54 elkserver kibana: at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:28:26)
Jun 27 10:41:54 elkserver kibana: at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:241:12)
Jun 27 10:41:54 elkserver kibana: at applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:514:14)
Jun 27 10:41:54 elkserver kibana: at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)
Jun 27 10:41:54 elkserver kibana: at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/CachePlugin.js:78:5)
Jun 27 10:41:54 elkserver kibana: at Compiler.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)
Jun 27 10:41:54 elkserver kibana: at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:511:11)
Jun 27 10:41:54 elkserver kibana: at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)
Jun 27 10:41:54 elkserver kibana: at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:671:19)
Jun 27 10:41:54 elkserver kibana: at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)
Jun 27 10:41:54 elkserver kibana: at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:662:11)
Jun 27 10:41:54 elkserver kibana: at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)
Jun 27 10:41:54 elkserver kibana: at Compilation.<anonymous> (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/index.js:244:6)
Jun 27 10:41:54 elkserver kibana: at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:204:14)
Jun 27 10:41:54 elkserver kibana: at Compilation.compilation.plugin (/usr/share/kibana/node_modules/webpack/lib/BannerPlugin.js:67:5)
Jun 27 10:41:54 elkserver kibana: at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)
Jun 27 10:41:54 elkserver kibana: at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:657:10)
Jun 27 10:41:54 elkserver kibana: at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)
Jun 27 10:41:54 elkserver kibana: at Compilation.<anonymous> (/usr/share/kibana/node_modules/extract-text-webpack-plugin/dist/index.js:275:11)
Jun 27 10:41:54 elkserver kibana: at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)
Jun 27 10:41:54 elkserver kibana: at sealPart2 (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:653:9)
Jun 27 10:41:54 elkserver kibana: cause:
Jun 27 10:41:54 elkserver kibana: { Error: Optimizations failure.
Jun 27 10:41:54 elkserver kibana: 6149 modules
Jun 27 10:41:54 elkserver kibana: #033[1m#033[31mERROR in /usr/share/kibana/plugins/kibana-datepicker/public/datepickerController.js
Jun 27 10:41:54 elkserver kibana: Module not found: Error: Can't resolve '@elastic/datemath' in '/usr/share/kibana/plugins/kibana-datepicker/public'#033[39m#033[22m
Jun 27 10:41:54 elkserver kibana: at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:245:27)
Jun 27 10:41:54 elkserver kibana: at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:28:26)
Jun 27 10:41:54 elkserver kibana: at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:241:12)
Jun 27 10:41:54 elkserver kibana: at applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:514:14)
Jun 27 10:41:54 elkserver kibana: at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)
Jun 27 10:41:54 elkserver kibana: at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/CachePlugin.js:78:5)
Jun 27 10:41:54 elkserver kibana: at Compiler.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)
Jun 27 10:41:54 elkserver kibana: at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:511:11)
Jun 27 10:41:54 elkserver kibana: at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)
Jun 27 10:41:54 elkserver kibana: at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:671:19)
Jun 27 10:41:54 elkserver kibana: at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:195:46)
Jun 27 10:41:54 elkserver kibana: at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:662:11)
Jun 27 10:41:54 elkserver kibana: at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)
Jun 27 10:41:54 elkserver kibana: at Compilation.<anonymous> (/usr/share/kibana/node_modules/uglifyjs-webpack-plugin/dist/index.js:244:6)
Jun 27 10:41:54 elkserver kibana: at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:204:14)
Jun 27 10:41:54 elkserver kibana: at Compilation.compilation.plugin (/usr/share/kibana/node_modules/webpack/lib/BannerPlugin.js:67:5)
Jun 27 10:41:54 elkserver kibana: at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)
Jun 27 10:41:54 elkserver kibana: at self.applyPluginsAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:657:10)
Jun 27 10:41:54 elkserver kibana: at next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:202:11)
Jun 27 10:41:54 elkserver kibana: at Compilation.<anonymous> (/usr/share/kibana/node_modules/extract-text-webpack-plugin/dist/index.js:275:11)
Jun 27 10:41:54 elkserver kibana: at Compilation.applyPluginsAsyncSeries (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:206:13)
Jun 27 10:41:54 elkserver kibana: at sealPart2 (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:653:9)
Jun 27 10:41:54 elkserver kibana: data:
Jun 27 10:41:54 elkserver kibana: { errors: [Array],
Jun 27 10:41:54 elkserver kibana: warnings: [],
Jun 27 10:41:54 elkserver kibana: version: '3.6.0',
Jun 27 10:41:54 elkserver kibana: hash: '510959a0de028c126342',
Jun 27 10:41:54 elkserver kibana: time: 533045,
Jun 27 10:41:54 elkserver kibana: publicPath: '__REPLACE_WITH_PUBLIC_PATH__',
Jun 27 10:41:54 elkserver kibana: assetsByChunkName: [Object],
Jun 27 10:41:54 elkserver kibana: assets: [Array],
Jun 27 10:41:54 elkserver kibana: filteredAssets: 0,
Jun 27 10:41:54 elkserver kibana: entrypoints: [Object],
Jun 27 10:41:54 elkserver kibana: chunks: [Array],
Jun 27 10:41:54 elkserver kibana: modules: [Array],
Jun 27 10:41:54 elkserver kibana: filteredModules: 0,
Jun 27 10:41:54 elkserver kibana: children: [Array] },
Jun 27 10:41:54 elkserver kibana: isBoom: true,
Jun 27 10:41:54 elkserver kibana: isServer: true,
Jun 27 10:41:54 elkserver kibana: output: { statusCode: 500, payload: [Object], headers: {} },
Jun 27 10:41:54 elkserver kibana: reformat: [Function],
Jun 27 10:41:54 elkserver kibana: typeof: [Function] },
Jun 27 10:41:54 elkserver kibana: isOperational: true,
Jun 27 10:41:54 elkserver kibana: data:
Jun 27 10:41:54 elkserver kibana: { errors:
Jun 27 10:41:54 elkserver kibana: [ '/usr/share/kibana/plugins/kibana-datepicker/public/datepickerController.js\nModule not found: Error: Can\'t resolve \'@elastic/datemath\' in \'/usr/share/kibana/plugins/kibana-datepicker/public\'\nresolve \'@elastic/datemath\' in \'/usr/share/kibana/plugins/kibana-datepicker/public\'\n  Parsed request is a module\n  using description file: /usr/share/kibana/plugins/kibana-datepicker/package.json (relative path: ./public)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n  after using description file: /usr/share/kibana/plugins/kibana-datepicker/package.json (relative path: ./public)\n    resolve as module\n      /usr/share/kibana/plugins/kibana-datepicker/public/webpackShims doesn\'t exist or is not a directory\n      /usr/share/kibana/plugins/kibana-datepicker/webpackShims doesn\'t exist or is not a directory\n      /usr/share/kibana/plugins/webpackShims doesn\'t exist or is not a directory\n      /usr/share/webpackShims doesn\'t exist or is not a directory\n      /usr/webpackShims doesn\'t exist or is not a directory\n      /webpackShims doesn\'t exist or is not a directory\n      looking for modules in /usr/share/kibana/webpackShims\n        using description file: /usr/share/kibana/package.json (relative path: ./webpackShims)\n          Field \'browser\' doesn\'t contain a valid alias configuration\n        after using description file: /usr/share/kibana/package.json (relative path: ./webpackShims)\n          using description file: /usr/share/kibana/package.json (relative path: ./webpackShims/@elastic/datemath)\n            no extension\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/webpackShims/@elastic/datemath doesn\'t exist\n            .js\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/webpackShims/@elastic/datemath.js doesn\'t exist\n            .json\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/webpackShims/@elastic/datemath.json doesn\'t exist\n            as directory\n              /usr/share/kibana/webpackShims/@elastic/datemath doesn\'t exist\n      looking for modules in /usr/share/kibana/webpackShims\n        using description file: /usr/share/kibana/package.json (relative path: ./webpackShims)\n          Field \'browser\' doesn\'t contain a valid alias configuration\n        after using description file: /usr/share/kibana/package.json (relative path: ./webpackShims)\n          using description file: /usr/share/kibana/package.json (relative path: ./webpackShims/@elastic/datemath)\n            no extension\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/webpackShims/@elastic/datemath doesn\'t exist\n            .js\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/webpackShims/@elastic/datemath.js doesn\'t exist\n            .json\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/webpackShims/@elastic/datemath.json doesn\'t exist\n            as directory\n              /usr/share/kibana/webpackShims/@elastic/datemath doesn\'t exist\n      /usr/share/kibana/plugins/kibana-datepicker/public/node_modules doesn\'t exist or is not a directory\n      /usr/share/kibana/plugins/kibana-datepicker/node_modules doesn\'t exist or is not a directory\n      /usr/share/kibana/plugins/node_modules doesn\'t exist or is not a directory\n      /usr/share/node_modules doesn\'t exist or is not a directory\n      /usr/node_modules doesn\'t exist or is not a directory\n      /node_modules doesn\'t exist or is not a directory\n      looking for modules in /usr/share kibana/node_modules\n        using description file: /usr/share/kibana/package.json (relative path: ./node_modules)\n          Field \'browser\' doesn\'t contain a valid alias configuration\n        after using description file: /usr/share/kibana/package.json (relative path: ./node_modules)\n          using description file: /usr/share/kibana/package.json (relative path: ./node_modules/@elastic/datemath)\n            no extension\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/node_modules/@elastic/datemath doesn\'t exist\n            .js\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/node_modules/@elastic/datemath.js doesn\'t exist\n            .json\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/node_modules/@elastic/datemath.json doesn\'t exist\n            as directory\n              /usr/share/kibana/node_modules/@elastic/datemath doesn\'t exist\n      looking for modules in /usr/share/kibana/node_modules\n        using description file: /usr/share/kibana/package.json (relative path: ./node_modules)\n          Field \'browser\' doesn\'t contain a valid alias configuration\n        after using description file: /usr/share/kibana/package.json (relative path: ./node_modules)\n          using description file: /usr/share/kibana/package.json (relative path: ./node_modules/@elastic/datemath)\n            no extension\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/node_modules/@elastic/datemath doesn\'t exist\n            .js\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/node_modules/@elastic/datemath.js doesn\'t exist\n            .json\n              Field \'browser\' doesn\'t contain a valid alias configuration\n              /usr/share/kibana/node_modules/@elastic/datemath.json doesn\'t exist\n            as directory\n              /usr/share/kibana/node_modules/@elastic/datemath doesn\'t exist\n[/usr/share/kibana/plugins/kibana-datepicker/public/webpackShims]\n[/usr/share/kibana/plugins/kibana-datepicker/webpackShims]\n[/usr/share/kibana/plugins/webpackShims]\n[/usr/share/webpackShims]\n[/usr/webpackShims]\n[/webpackShims]\n[/usr/share/kibana/webpackShims/@elastic/datemath]\n[/usr/share/kibana/webpackShims/@elastic/datemath.js]\n[/usr/share/kibana/webpackShims/@elastic/datemath.json]\n[/usr/share/kibana/webpackShims/@elastic/datemath]\n[/usr/share/kibana/webpackShims/@elastic/datemath]\n[/usr/share/kibana/webpackShims/@elastic/datemath.js]\n[/usr/share/kibana/webpackShims/@elastic/datemath.json]\n[/usr/share/kibana/webpackShims/@elastic/datemath]\n[/usr/share/kibana/plugins/kibana-datepicker/public/node_modules]\n[/usr/share/kibana/plugins/kibana-datepicker/node_modules]\n[/usr/share/kibana/plugins/node_modules]\n[/usr/share/node_modules]\n[/usr/node_modules]\n[/node_modules]\n[/usr/share/kibana/node_modules/@elastic/datemath]\n[/usr/share/kibana/node_modules/@elastic/datemath.js]\n[/usr/share/kibana/node_modules/@elastic/datemath.json]\n[/usr/share/kibana/node_modules/@elastic/datemath]\n[/usr/share/kibana/node_modules/@elastic/datemath]\n[/usr/share/kibana/node_modules/@elastic/datemath.js]\n[/usr/share/kibana/node_modules/@elastic/datemath.json]\n[/usr/share/kibana/node_modules/@elastic/datemath]\n @ /usr/share/kibana/plugins/kibana-datepicker/public/datepickerController.js 7:16-44\n @ /usr/share/kibana/plugins/kibana-datepicker/public/datepicker.js\n @ /usr/share/kibana/optimize/bundles/kibana.entry.js' ],
Jun 27 10:41:54 elkserver kibana: warnings: [],
Jun 27 10:41:54 elkserver kibana: version: '3.6.0',
Jun 27 10:41:54 elkserver kibana: hash: '510959a0de028c126342',
Jun 27 10:41:54 elkserver kibana: time: 533045,`

Regards,

Rafael

**Comment by esequiasneto** [comment]
Its work in Kibana 6.5.4
